spring:
  datasource:
    url: jdbc:mysql://47.106.247.242:3306/VeinServer?useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: huanjing
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
server:
  tomcat:
    connection-timeout: 180000 #连接时间
    max-http-form-post-size: 500MB
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
